---
- name: Deploy Headscale
  hosts: luxembourg
  become: true
  vars:
    root_directory: /opt/headscale
    compose_file_source: ../../compose/headscale/compose.yml
    compose_file_destination: "{{ root_directory }}/compose.yml"

  tasks:
    - name: Ensure Headscale directory exists
      ansible.builtin.file:
        path: "{{ root_directory }}"
        state: directory
        mode: "0750"
        owner: root
        group: root

    - name: Copy docker-compose file
      ansible.builtin.copy:
        src: "{{ compose_file_source }}"
        dest: "{{ compose_file_destination }}"
        mode: "0640"
        owner: root
        group: root

    - name: Deploy Headscale with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ root_directory }}"
        state: present
