---
- name: Setup replication from bruxelles to other sites
  hosts:
    - paris
    - pristina
  become: true
  vars:
    bruxelles_host: "local.bruxelles.anneraud.fr"
    bruxelles_user: "ansible"

    service_name: "bruxelles-replicate"
  vars_files:
    - ../../vault/ansible/vault.yml
    - ../../vault/replication/vault.yml
  tasks:
    - name: Create the systemd service unit
      ansible.builtin.copy:
        dest: "/etc/systemd/system/{{ service_name }}.service"
        mode: "0640"
        content: |
          [Unit]
          Description=Trigger TrueNAS Replication Task
          After=network-online.target
          Wants=network-online.target

          [Service]
          Type=oneshot
          User=ansible
          Group=ansible
          BatchMode=yes # Disable password prompts

          ExecStart=/usr/bin/ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new {{ bruxelles_user }}@{{ bruxelles_host }} 'midclt -K {{ bruxelles_api_key }} call replication.run {{ bruxelles_replication_identifier }}'

    - name: Create the systemd timer unit
      ansible.builtin.copy:
        dest: "/etc/systemd/system/{{ service_name }}.timer"
        mode: "0644"
        content: |
          [Unit]
          Description=Run replication of bruxelles (Desktop Optimized)

          [Timer]
          OnCalendar=*-*-* 00/12:00:00
          Persistent=true
          RandomizedDelaySec=5min

          [Install]
          WantedBy=timers.target

    - name: Enable and start the timer
      ansible.builtin.systemd:
        name: "{{ service_name }}.timer"
        state: started
        enabled: true
        daemon_reload: true

    - name: Ensure the service itself is enabled (but not necessarily started)
      ansible.builtin.systemd:
        name: "{{ service_name }}.service"
        enabled: true
