---
# Homepage configuration
# See https://fontawesome.com/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Acceuil - Anneraud"
subtitle: "Services souverains de la famille Anneraud"
documentTitle: "Bienvenue sur les services souverains de la famille Anneraud" # Customize the browser tab text

#logo: "assets/logo.png"
# Alternatively a fa icon can be provided:
#icon: "fas fa-network-wired"

header: true # Set to false to hide the header
# Optional: Different hotkey for search, defaults to "/"
# hotkey:
#   search: "Shift"
footer: '<p>Administré par <a href="https://alix.anneraud.fr/">Alix ANNERAUD</a></p>' # set false if you want to hide it.

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
                        # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

# Optional: Proxy / hosting option
proxy:
  useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level. 
  headers: # send custom headers when fetching service specific data. Can also be set on a service level.
    Test: "Example"
    Test1: "Example1"


# Set the default layout and color scheme
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.

# Optional custom stylesheet
# Will load custom CSS files. Especially useful for custom icon sets.
# stylesheet:
#   - "assets/custom.css"

# Here is the exhaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "/assets/your/light/bg.png" # prefix with your sub subpath if any (ex: /homer/assets/...)
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "/assets/your/dark/bg.png" # prefix with your sub subpath if any (ex: /homer/assets/...)

# Optional message
message:
  style: "is-success"
  title: "Bienvenue sur les services souverains de la famille Anneraud !"
  icon: "fas fa-home"
  # The content also accepts HTML content, so you can add divs, images or whatever you want to make match your needs.
  content: "Accédez à tous vos services hébergés localement. <strong>Services VPN</strong> nécessitent une connexion Tailscale. Consultez l'<a href='https://etat.anneraud.fr/' target='_blank'>état des services</a> pour vérifier leur disponibilité."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "État"
    icon: "fas fa-heartbeat"
    url: "https://etat.anneraud.fr/"
    target: "_blank" 


services:
  - name: "Services"
    icon: "fas fa-code-branch"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    # class: "highlight-purple" # Optional css class to add on the service group. 
    items:
      - name: "Nuage"
        icon: "fas fa-cloud"
        subtitle: "Hébergement de fichiers"
        keywords: "self hosted nuage nextcloud" 
        url: "https://nuage.anneraud.fr"
        target: "_blank" 
      - name: "Galerie"
        icon: "fas fa-image"
        subtitle: "Hébergement de photos"
        keywords: "self hosted photos immich"
        url: "https://galerie.anneraud.fr"
        target: "_blank"
      - name: "Maison"
        icon: "fas fa-home"
        subtitle: "Gérez la maison"
        url: "https://maison.anneraud.fr"
      - name: "Bitwarden"
        icon: "fas fa-key"
        subtitle: "Gestionnaire de mots de passe"
        keywords: "self hosted bitwarden password"
        url: "https://bitwarden.anneraud.fr"
        target: "_blank"
      - name: "Archives"
        icon: "fas fa-box-archive"
        subtitle: "Hébergement de documents"
        tag: "VPN"
        keywords: "self hosted archive paperless"
        url: "https://archive.anneraud.fr"
        target: "_blank"
      - name: "Finances"
        icon: "fas fa-coins"
        subtitle: "Gérez vos finances"
        tag: "VPN"
        url: "https://finances.anneraud.fr"
      - name: "Importateur finances"
        icon: "fas fa-file-import"
        subtitle: "Firefly III importer"
        tag: "VPN"
        url: "https://importeur-finances.anneraud.fr"
        target: "_blank"
      - name: "Statistiques"
        icon: "fas fa-chart-bar"
        subtitle: "Umami - Statistiques web"
        url: "https://s.anneraud.fr"
        target: "_blank"
      - name: "Notes"
        icon: "fas fa-sticky-note"
        subtitle: "Docmost - Documentation"
        tag: "VPN"
        url: "https://notes.anneraud.fr"
        target: "_blank"
      - name: "Arnaud"
        icon: "fas fa-building"
        subtitle: "Odoo - ERP"
        tag: "VPN"
        url: "https://arnaud.anneraud.fr"
        target: "_blank"
      - name: "Git"
        icon: "fas fa-code-branch"
        subtitle: "Gitea - Dépôts Git"
        tag: "VPN"
        url: "https://git.anneraud.fr"
        target: "_blank"
      - name: "Recettes"
        icon: "fas fa-utensils"
        subtitle: "Mealie - Recettes de cuisine"
        tag: "VPN"
        url: "https://recettes.anneraud.fr"
        target: "_blank"
      - name: "Automatisations"
        icon: "fas fa-robot"
        subtitle: "n8n - Automatisations"
        tag: "VPN"
        url: "https://automatisation.anneraud.fr"
        target: "_blank"
      - name: "Portefolio Alix"
        icon: "fas fa-user"
        subtitle: "GitHub Pages"
        url: "https://alix.anneraud.fr"
        target: "_blank"
      - name: "Wakapi"
        icon: "fas fa-clock"
        subtitle: "Statistiques d'utilisation"
        url: "https://wakapi.anneraud.fr"
        target: "_blank"

  - name: "Divertissement"
    items:
      - name: "Médiathèque"
        icon: "fas fa-film"
        subtitle: "Films, séries et musique"
        keywords: "self hosted media jellyfin"
        url: "https://mediatheque.anneraud.fr"
        target: "_blank"
      - name: "Radarr"
        icon: "fas fa-film"
        subtitle: "Gestionnaire de films"
        tag: "VPN"
        url: "https://radarr.anneraud.fr"
        target: "_blank"
      - name: "Sonarr"
        icon: "fas fa-tv"
        subtitle: "Gestionnaire de séries"
        tag: "VPN"
        url: "https://sonarr.anneraud.fr"
        target: "_blank"
      - name: "Prowlarr"
        icon: "fas fa-search"
        subtitle: "Indexeur de contenu"
        tag: "VPN"
        url: "https://prowlarr.anneraud.fr"
        target: "_blank"
      - name: "Bazarr"
        icon: "fas fa-closed-captioning"
        subtitle: "Gestionnaire de sous-titres"
        tag: "VPN"
        url: "https://bazarr.anneraud.fr"
        target: "_blank"
      - name: "Jellyseerr"
        icon: "fas fa-plus-circle"
        subtitle: "Demandes de contenu"
        tag: "VPN"
        url: "https://jellyseerr.anneraud.fr"
        target: "_blank"
    icon: "fas fa-masks-theater"
    
  - name: "Infrastructure"
    icon: "fas fa-network-wired"
    items:
      - name: "Console Bruxelles"
        icon: "fas fa-server"
        tag: "VPN"
        url: "https://bruxelles.anneraud.fr"
        target: "_blank"
      - name: "Tailscale console"
        icon: "fas fa-shield-alt"
        url: "https://tailscale.anneraud.fr/admin"
        target: "_blank"
      - name: "Proxy Bruxelles"
        icon: "fas fa-server"
        subtitle: "Nginx Proxy Manager"
        tag: "VPN"
        url: "https://nginx.bruxelles.anneraud.fr"
        target: "_blank"
      - name: "DNS dynamique Bruxelles"
        icon: "fas fa-globe"
        subtitle: "DDNS updater"
        tag: "VPN"
        url: "https://ddns-updater.bruxelles.anneraud.fr"
        target: "_blank"
      - name: "VPN"
        icon: "fas fa-shield-alt"
        subtitle: "Tailscale - Réseau privé"
        url: "https://tailscale.anneraud.fr"
        target: "_blank"
      - name: "Conteneurs Bruxelles"
        icon: "fas fa-cube"
        subtitle: "Portainer - Gestion Docker"
        tag: "VPN"
        url: "https://conteneurs.bruxelles.anneraud.fr"
        target: "_blank"