services:
  docmost:
    image: docmost/docmost:0.95
    depends_on:
      - db
      - redis
    environment:
      APP_URL: ${APP_URL}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "30101:3000"
    restart: unless-stopped
    volumes:
      - ./Storage:/app/data/storage
    networks:
      - internal

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./Postgres_data:/var/lib/postgresql
    networks:
      - internal
      - databases

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - ./Redis_data:/data
    networks:
      - internal

networks:
  internal:
  databases:
    external: true
