---
- name: Deploy Notes
  hosts: bruxelles
  become: true
  vars:
    root_directory: /mnt/Donnees/Applications/Docmost
    compose_file_source: ../../compose/docmost/compose.yml
    compose_file_destination: "{{ root_directory }}/compose.yml"
    environment_file_source: ../../configurations/notes/.env
    environment_file_destination: "{{ root_directory }}/.env"
    user_id: 568
    group_id: 568

  tasks:
    - name: Copy compose file
      ansible.builtin.copy:
        src: "{{ compose_file_source }}"
        dest: "{{ compose_file_destination }}"
        mode: "0640"
        owner: "{{ user_id }}"
        group: "{{ group_id }}"

    - name: Copy environment file
      ansible.builtin.copy:
        src: "{{ environment_file_source }}"
        dest: "{{ environment_file_destination }}"
        mode: "0640"
        owner: "{{ user_id }}"
        group: "{{ group_id }}"

    - name: Deploy Notes with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ root_directory }}"
        pull: always
        recreate: always
        remove_orphans: true
        state: present
