services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp #
      - 30096:30096/tcp # Transmission WebUI
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ${VPN_PROFILE_PATH}:/gluetun/custom.ovpn:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.ovpn
      - OPENVPN_USER=${VPN_USER_NAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=568
      - PGID=3010
      - TZ=Etc/UTC
      - WEBUI_PORT=30096
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIGURATION_PATH}:/config
      - ${DOWNLOADS_PATH}:/data/torrents #optional
    #    ports:
    #      - 8080:8080
    #      - 6881:6881
    #      - 6881:6881/udp
    restart: unless-stopped
