storage:
  type: postgres
  path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"

ui:
  title: "Tableau de bord | Anneraud"
  description: "Tableau de bord des services souverain de la famille Anneraud"
  header: "Tableau de bord"
  logo: ""
  default-sort-by: group

alerting:
  homeassistant:
    url: "${HOME_ASSISTANT_URL}" # URL of your HomeAssistant instance
    token: "${HOME_ASSISTANT_TOKEN}" # Long-lived access token from HomeAssistant
    default-alert:
      enabled: true
      send-on-resolved: true
      failure-threshold: 1
      success-threshold: 1

endpoints:
  - name: Bitwarden (Nextcloud)
    group: Services
    url: "https://bitwarden.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Nuage (Nextcloud)
    group: Services
    url: "https://nuage.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Galerie (Immich)
    group: Services
    url: "https://galerie.anneraud.fr"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Automatisation (n8n)
    group: Services
    url: "https://automatisation.anneraud.fr/healthz"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[BODY].status == ok"
    alerts:
      - type: homeassistant

  - name: Maison (Home Assistant)
    group: Services
    url: "https://maison.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Médiathèque (Jellyfin)
    group: Services
    url: "https://maison.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Archive (Paperless-ngx)
    group: Services
    url: "https://maison.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Proxy Bruxelles (Nginx Proxy Manager)
    group: Infrastructure
    url: "https://nginx.bruxelles.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: DNS dynamique Bruxelles (DDNS updater)
    group: Infrastructure
    url: "https://ddns-updater.bruxelles.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: VPN (Tailscale)
    group: Infrastructure
    url: "https://tailscale.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 404"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: VPN console
    group: Services
    url: "https://tailscale.anneraud.fr/admin/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Statistiques (Umami)
    group: Services
    url: "https://s.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Notes (Docmost)
    group: Services
    url: "https://notes.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Arnaud (Odoo)
    group: Services
    url: "https://arnaud.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Git (Gitea)
    group: Services
    url: "https://git.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Finances (Firefly III)
    group: Services
    url: "https://finances.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Importateur finances (Firefly III importer)
    group: Services
    url: "https://importeur-finances.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Recettes (Mealie)
    group: Services
    url: "https://recettes.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Portefolio Alix (GitHub Pages)
    group: Services
    url: "https://alix.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Bruxelles console (TrueNAS)
    group: Infrastructure
    url: "https://bruxelles.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Radarr
    group: Services
    url: "https://radarr.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Sonarr
    group: Services
    url: "https://sonarr.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Prowlarr
    group: Services
    url: "https://prowlarr.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Bazarr
    group: Services
    url: "https://bazarr.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Jellyseerr
    group: Services
    url: "https://jellyseerr.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Conteneurs Bruxelles (Portainer)
    group: Infrastructure
    url: "https://conteneurs.bruxelles.anneraud.fr/"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: homeassistant

  - name: Wakapi
    group: Services
    url: "https://wakapi.anneraud.fr/api/health"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[BODY] == pat(*app=1*)"
      - "[BODY] == pat(*db=1*)"
    alerts:
      - type: homeassistant

  - name: Bruxelles
    url: "icmp://local.bruxelles.anneraud.fr"
    group: Infrastructure
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: homeassistant

  - name: Luxembourg
    url: "icmp://local.luxembourg.anneraud.fr"
    group: Infrastructure
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: homeassistant
